export EDITOR='emacs -nw'

# History
export HISTFILE=~/.zsh_history
export HISTSIZE=50000
export SAVEHIST=10000
export HISTTIMEFORMAT="[%F %T] "
setopt inc_append_history
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

alias be='bundle exec'
alias emc='emacs -nw'
alias sudo='sudo '
alias t='dev test $(git ls-files | sed -n /_test.rb$/p | fzf)'
alias cop='be bin/rubocop -a'

export LESS=-RSFX

# load asdf, but only if present and the shell is interactive
if [[ -f $HOME/.asdf/asdf.sh ]] && [[ $- == *i* ]]; then
  . $HOME/.asdf/asdf.sh
fi

# manually inserted binaries
export PATH="$HOME/bin:$PATH"

# add cabal binaries to path
export PATH="$PATH:$HOME/.cabal/bin"


# load dev, but only if present and the shell is interactive
if [[ -f /opt/dev/dev.sh ]] && [[ $- == *i* ]]; then
  source /opt/dev/dev.sh
fi

if [ -r "$HOME/.github-token.sh" ]; then
  source "$HOME/.github-token.sh"
else
  printf "zsh init warning: $HOME/.github-token.sh not found\n"
fi

# Interactive prompt
autoload -Uz vcs_info
precmd_functions+=( vcs_info )
setopt prompt_subst

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats '%F{200}[%b%u%c]%f'
zstyle ':vcs_info:*' enable git

PROMPT='%(?.%F{green}√.%F{red}?%?)%f %B%~%b $vcs_info_msg_0_ $ '